version: "3"

tasks:
  migrate:
    aliases:
      - migrate
    desc: Run migration utility
    cmds:
      - go run ./cmd/migrator -storage-path="./storage/storage.db" -migrations-path="./migrations"
  run:
    aliases:
      - run
    desc: run grpc service
    cmds:
      - go run ./cmd/sso --conf="./config/local.yml"
  register:
    aliases:
      - register
    desc: register new user. USAGE NAME="c@a.a" task register 
    cmds:
      - grpcurl -plaintext -d '{"username":"{{.NAME}}", "password":"123"}' localhost:44044 auth.Auth/Register
      
      